name: Bump tunnel

on:
  workflow_dispatch:
    inputs:
      tunnel_version:
        required: true
        type: string
        description: the tunnel version

run-name: Bump tunnel to v${{ inputs.tunnel_version }}

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Tunnel versions
        run: |
          sed -r -i "s/ghcr.io\/khulnasoft\/tunnel:[0-9]+\.[0-9]+\.[0-9]+/ghcr.io\/khulnasoft\/tunnel:${{ inputs.tunnel_version }}/" Dockerfile
          sed -r -i "s/TUNNEL_VERSION: [0-9]+\.[0-9]+\.[0-9]+/TUNNEL_VERSION: ${{ inputs.tunnel_version }}/" .github/workflows/build.yaml
          find test/data -type f -name '*.test' | xargs sed -r -i 's/"version": "[0-9]+\.[0-9]+\.[0-9]+"/"version": "${{ inputs.tunnel_version }}"/'

      - name: Create PR
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.ORG_REPO_TOKEN }}
          title: "chore(deps): Update tunnel to v${{ inputs.tunnel_version }}"
          commit-message: "chore(deps): Update tunnel to v${{ inputs.tunnel_version }}"
          committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch-suffix: timestamp
          branch: bump-tunnel
          delete-branch: true

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.create-pr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.create-pr.outputs.pull-request-url }}"
